### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [Saikat-98/Text-transator#8]
Like this
![image](https://user-images.githubusercontent.com/68433936/104811895-9cf06800-5824-11eb-9c5c-866fc7311857.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by shrushti2000** [comment]
I would like to work on this

**Comment by bharath-acchu** [comment]
@shrushti2000  can I work on this?

**Comment by vismitap** [comment]
Hey! Can I work on this issue?

**Comment by jatinjain001** [comment]
Can I work on this issue please.

**Comment by Swapnil-Gaur** [comment]
Can I work on this?

**Comment by Dhriti-Roy** [comment]
can I work on this ??

**Comment by anirudhsai20** [comment]
Hi @Saikat-98 . Can I please work on this issue under DWOC?
